config/routes.rb
CanadaTimeTracker::Application.routes.draw do
  resources :days

  devise_for :users
  
  root  "days#index"
  get   'how_it_works'  =>  'pages#how_it_works'
  

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many  :days
         
  validates :name, presence: true
  validates :user_country, presence: true
  
  
  # \A matches beginning of string, where [^@\s] means @ should ONLY precede capgemini, as it's ensuring that it's not matched for this.
  validates_format_of :email, :with => /\A([^@\s]+)@(capgemini\.com)\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :user_country
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = current_user.days.build
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = current_user.days.build(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:days_in_canada_this_year, :days_in_canada_last_year, :days_in_canada_tax)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :days_in_canada_this_year %><br>
    <%= f.number_field :days_in_canada_this_year %>
  </div>
  <div class="field">
    <%= f.label :days_in_canada_last_year %><br>
    <%= f.number_field :days_in_canada_last_year %>
  </div>
  <div class="field">
    <%= f.label :days_in_canada_tax %><br>
    <%= f.number_field :days_in_canada_tax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<%= render 'pages/index' unless user_signed_in? %>

<div class="jumbotron center">
	<h1>Listing days</h1>

		<table>
		  <thead>
		    <tr>
		      <th>Canada This Year</th>
		      <th>Canada Last Year</th>
		      <th>Taxable Days</th>
					<th>User Id</th>
		      <th></th>
		      <th></th>
		      <th></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @days.each do |day| %>
					<% if day.user == current_user %>
		      	<tr>
			        <td><%= day.days_in_canada_this_year %></td>
			        <td><%= day.days_in_canada_last_year %></td>
			        <td><%= day.days_in_canada_tax %></td>
							<td><%= day.user.email if day.user %></td>
			        <td><%= link_to 'Show', day %></td>
			        <td><%= link_to 'Edit', edit_day_path(day) %></td>
			        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			      </tr>
			    <% end %><!-- end conditional if -->
				<% end %><!-- end going through all users -->
		  </tbody>
		</table>

		<br>

		<!-- >   <%= link_to 'New Day', new_day_path %>   < -->
			
</div><!-- /. jumbotron -->

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Days in canada this year:</strong>
  <%= @day.days_in_canada_this_year %>
</p>

<p>
  <strong>Days in canada last year:</strong>
  <%= @day.days_in_canada_last_year %>
</p>

<p>
  <strong>Days in canada tax:</strong>
  <%= @day.days_in_canada_tax %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
			<%= link_to "Canada Time Tracker", root_path, class: "navbar-brand" %>
	  </div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "How it Works", how_it_works_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Account Settings", edit_user_registration_path %></li>
					<% end %>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Canada Time Tracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info")%>
		<% end %>
		
		<%= yield %>
		<div class = "center">
			<h6>Copyright &copy; 2014 Canada Time Tracker. All rights reserved.</h6>
		</div>	
	</div>

</body>
</html>

app/views/pages/_index.html.erb
<div class="jumbotron center">
	<h2>Keep track of your days in Canada with ease</h2>
		<p><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
		<p>Already have an account? <%= link_to "Sign in", new_user_session_path %></p>
</div>

<!-- /.jumbotron>

app/views/pages/index.html.erb
<div class="jumbotron center">
	<h2>Keep track of your days in Canada with ease</h2>
		<p><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
		<p>Already have an account? <%= link_to "Sign in", new_user_session_path %></p>
</div><!-- /.jumbotron>